### ISSUE TITLE
actions for ProfileAvatarView.PROFILE_AVATAR_CLICKED_MENU does not show menu when clicked on title

### ISSUE THREAD

**Issue by arthef** [shannah/RADChatRoom#11]
I am following the tutorial and I am at the "Adding Phone and Video Conferencing" part. I used the code:
``` java
ViewNode viewNode = new ViewNode(
    actions(ChatRoomView.SEND_ACTION, send),
    actions(ProfileAvatarView.PROFILE_AVATAR_CLICKED_MENU, phone, videoConference) 
);
```
To add context menu for phone calls and videoconferencing. According to tutorial this should enable menu when clicked on title or on buble avatar. However, for me the menu only shows when I click on bubble avatar. Nothing happens when I click on title.

**Comment by shannah** [comment]
Fixed https://github.com/shannah/CodeRAD/commit/67252c6cfcbe2e66de1a7e29a90b6d98e4fe3658

**Comment by arthef** [comment]
Just an update on this. I have refreshed all project libraries and cn1 libs and this still does not work. There is no context/popup menu showing when clicked on avatar in the title.

**Comment by shannah** [comment]
Can't reproduce.  I've added participants to the RADChatRoomTest3 sample to verify.  Please start with that sample and make it not work.
Or post a self-contained test case that can reproduce this issue.

**Comment by arthef** [comment]
Hi, the chat sample works as expected. I have just recompiled CodeRad from sources on my computer and copied library over to my project and now it also works as expected.
Looks like, for some reason, I was stuck with old libraries before.
